apiVersion: v2
name: taskmaster
description: TaskMaster AI - Full-stack task management with AI assistance
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - taskmaster
  - ai
  - task-management
  - fastapi
  - nextjs
maintainers:
  - name: TaskMaster Team
home: https://github.com/yourusername/taskmaster
sources:
  - https://github.com/yourusername/taskmaster
